name: Deploy # 部署
 
on: # 触发条件
  push:
    branches:
      - main # 推送到 main 分支（这里的分支名很重要，不要弄错了）
 
  release:
    types:
      - published # 推送新版本号
 
  workflow_dispatch: # 手动触发
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout # Checkout 仓库
      uses: actions/checkout@v2
      with:
        ref: main
 
    - name: Setup Node # 安装 Node.js
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"
 
    - name: Install Hexo # 安装 Hexo
      run: |
        npm install hexo-cli -g
    
    - name: Cache Modules # 缓存 Node 插件
      uses: actions/cache@v1
      id: cache-modules
      with:
        path: node_modules
        key: ${{runner.OS}}-${{hashFiles('**/package-lock.json')}}
 
    - name: Install Dependencies # 如果没有缓存或 插件有更新，则安装插件
      if: steps.cache-modules.outputs.cache-hit != 'true'
      run: | # npm ci老出错，不用了，直接用npm install
        npm install
    
    - name: check path
      run: | # 验证各部分的实际路径，以进行后续操作
        pwd
        cd ..
        pwd
        mkdir post
        cd post
        pwd
    - name: Get post part
      run: | # 复制post
        cd ..
        cp -r /home/runner/work/blog-source/blog-source/source/_posts /home/runner/work/blog-source/post
      
    - name: Git init
      run: |
        git config --global user.name "hehysh"
        git config --global user.email "hehysh@163.com"
        pwd
        cd /home/runner/work/blog-source/post
        git init
        git add .
        git commit -m "new post"
        git branch -M main
        git remote add origin https://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@github.com/hehysh/post.git
        git push -u origin main
